version: '3.5'

services:
  memcached1:
      image: memcached:latest
      container_name: nano-memcached1
      restart: always
      networks:
        backend:

  memcached2:
      image: memcached:latest
      container_name: nano-memcached2
      restart: always
      networks:
        backend:

networks:
  backend:
    driver: bridge